/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ClientFrame;
import java.awt.Color;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Group;
import model.User;

/**
 *
 * @author Chuong
 */
public class AddGroupForm extends javax.swing.JFrame {

    /**
     * Creates new form AddGroupForm
     */
    private Socket socket;
    private ObjectInputStream ois;
    private ObjectOutputStream oos;
    private ArrayList<Group> listGroup;
    private Group newGroup;
    private User user;
    private ArrayList<User> listFriendSearch,listMemberGourp;
    public AddGroupForm(User user, ObjectOutputStream oos, ObjectInputStream ois) throws IOException, ClassNotFoundException {
        listFriendSearch = new ArrayList<>();
        listMemberGourp=new ArrayList<>();
        this.ois = ois;
        this.oos = oos;
        this.user = user;
        oos.writeObject("CMD_CREATE_GROUP|"+user.getUserId());
        newGroup=(Group) ois.readObject();
        System.out.println(newGroup.getGroupId());
        initComponents();
    }

    public void connectToServer() {   //mỗi lần connect tới server là khởi tạo lại thuộc tính socketOfClient
        try {

            oos = new ObjectOutputStream(socket.getOutputStream());
            ois = new ObjectInputStream(socket.getInputStream());

        } catch (java.net.UnknownHostException e) {
            JOptionPane.showMessageDialog(this, "Host IP is not correct.\nPlease try again!", "Failed to connect to server", JOptionPane.ERROR_MESSAGE);
        } catch (java.net.ConnectException e) {
            JOptionPane.showMessageDialog(this, "Server is unreachable, maybe server is not open yet, or can't find this host.\nPlease try again!", "Failed to connect to server", JOptionPane.ERROR_MESSAGE);
        } catch (java.net.NoRouteToHostException e) {
            JOptionPane.showMessageDialog(this, "Can't find this host!\nPlease try again!", "Failed to connect to server", JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
            Logger.getLogger(ClientFrame.class.getName()).log(Level.SEVERE, null, ex);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        edtNameOfGroup = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFriend = new javax.swing.JTable();
        btnCancel = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMember = new javax.swing.JTable();
        edtSearch = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Create Group");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Create group");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Name group:");

        edtNameOfGroup.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        edtNameOfGroup.setForeground(new java.awt.Color(153, 153, 153));
        edtNameOfGroup.setText("Name of group");
        edtNameOfGroup.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                edtNameOfGroupFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                edtNameOfGroupFocusLost(evt);
            }
        });
        edtNameOfGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtNameOfGroupActionPerformed(evt);
            }
        });

        tblFriend.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblFriend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFriendMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblFriend);

        btnCancel.setBackground(new java.awt.Color(255, 255, 255));
        btnCancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnCreate.setBackground(new java.awt.Color(255, 255, 255));
        btnCreate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        tblMember.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMemberMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblMember);

        edtSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        edtSearch.setForeground(new java.awt.Color(153, 153, 153));
        edtSearch.setText("Search");
        edtSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                edtSearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                edtSearchFocusLost(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Member:");

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_tim_kiem.png"))); // NOI18N
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(309, 309, 309))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCreate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(edtSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(edtNameOfGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(418, 418, 418)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(18, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(edtNameOfGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(edtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnCreate))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(193, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(55, 55, 55)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void edtNameOfGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtNameOfGroupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtNameOfGroupActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        try {
            // TODO add your handling code here:
            oos.writeObject("CMD_REMOVE_CREATE_GROUP|"+newGroup.getGroupId());
//        (new HomeForm()).setVisible(true);
//        this.dispose();
        } catch (IOException ex) {
            Logger.getLogger(AddGroupForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        try {
            // TODO add your handling code here:
            oos.writeObject("CMD_SAVE_GROUP|"+edtNameOfGroup.getText().toString());
            newGroup.setNameGroup(edtNameOfGroup.getText().toString());
            listGroup.add(newGroup);
//        (new HomeForm()).setVisible(true);
//        this.dispose();
        } catch (IOException ex) {
            Logger.getLogger(AddGroupForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseClicked
        // TODO add your handling code here:
        String keySearch = edtSearch.getText().toString();
        try {
            oos.writeObject("CMD_SEARCH_FRIEND|"+user.getUserId()+"|" + keySearch);
        } catch (IOException ex) {
            Logger.getLogger(AddFriendForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            listFriendSearch = (ArrayList<User>) ois.readObject();
        } catch (IOException ex) {
            Logger.getLogger(AddFriendForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddFriendForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (listFriendSearch.size() != 0) {
            showDataFriendSearch();
        }
    }//GEN-LAST:event_btnSearchMouseClicked

    public void showDataFriendSearch(){
        DefaultTableModel dtm = new DefaultTableModel();
            dtm.setRowCount(0);
            dtm.setColumnIdentifiers(new String[]{"Nick Name"});

            for (User user : listFriendSearch) {
                    dtm.addRow(new String[]{user.getName()});
            }
            tblFriend.setModel(dtm);
    }
     public void showDataMemberGroup(){
        DefaultTableModel dtm = new DefaultTableModel();
            dtm.setRowCount(0);
            dtm.setColumnIdentifiers(new String[]{"Nick Name"});

            for (User user : listMemberGourp) {
                    dtm.addRow(new String[]{user.getName()});
            }
            tblMember.setModel(dtm);
    }
    
    private void tblFriendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFriendMouseClicked
        // TODO add your handling code here:
        int column = tblFriend.getColumnModel().
                getColumnIndexAtX(evt.getX()); // get the coloum of the button
        int row = evt.getY() / tblFriend.getRowHeight(); // get row 
        // *Checking the row or column is valid or not
        if (row < tblFriend.getRowCount() && row >= 0
                && column < tblFriend.getColumnCount() && column >= 0) {
            User actionUser = listFriendSearch.get(row);
                int choice = JOptionPane.showConfirmDialog(this, "Do you want add friend " + actionUser.getName() + " into group ?", "Ask", JOptionPane.YES_NO_OPTION);
                if (choice == JOptionPane.YES_OPTION) {
                    if(!listMemberGourp.contains(actionUser)){
                     listMemberGourp.add(actionUser);
                        try {
                            oos.writeObject("CMD_ADD_MEMBER|"+newGroup.getGroupId()+"|"+actionUser.getUserId());
                        } catch (IOException ex) {
                            Logger.getLogger(AddGroupForm.class.getName()).log(Level.SEVERE, null, ex);
                        }
                     showDataMemberGroup();
                    }else{
                        JOptionPane.showMessageDialog(this, "User was added into this group!");
                    }
                }
        }
    }//GEN-LAST:event_tblFriendMouseClicked

    private void tblMemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMemberMouseClicked
        // TODO add your handling code here:
        int column = tblMember.getColumnModel().
                getColumnIndexAtX(evt.getX()); // get the coloum of the button
        int row = evt.getY() / tblMember.getRowHeight(); // get row 
        // *Checking the row or column is valid or not
        if (row < tblMember.getRowCount() && row >= 0
                && column < tblMember.getColumnCount() && column >= 0) {
            User actionUser = listMemberGourp.get(row);
                int choice = JOptionPane.showConfirmDialog(this, "Do you want remove friend " + actionUser.getName() + " in group ?", "Ask", JOptionPane.YES_NO_OPTION);
                if (choice == JOptionPane.YES_OPTION) {
                     listMemberGourp.remove(actionUser);
                try {
                    oos.writeObject("CMD_REMOVE_MEMBER|"+newGroup.getGroupId()+"|"+actionUser.getUserId());
                } catch (IOException ex) {
                    Logger.getLogger(AddGroupForm.class.getName()).log(Level.SEVERE, null, ex);
                }
                     showDataMemberGroup();
                }
        }
    }//GEN-LAST:event_tblMemberMouseClicked

    private void edtSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtSearchFocusGained
        // TODO add your handling code here:
        
        if (edtSearch.getText().equals("username")) {
            edtSearch.setText("");
            edtSearch.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_edtSearchFocusGained

    private void edtSearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtSearchFocusLost
        // TODO add your handling code here:
        if (edtSearch.getText().equals("")) {
            edtSearch.setText("username");
            edtSearch.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_edtSearchFocusLost

    private void edtNameOfGroupFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtNameOfGroupFocusGained
        // TODO add your handling code here:
        if (edtNameOfGroup.getText().equals("username")) {
            edtNameOfGroup.setText("");
            edtNameOfGroup.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_edtNameOfGroupFocusGained

    private void edtNameOfGroupFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtNameOfGroupFocusLost
        // TODO add your handling code here:
        if (edtNameOfGroup.getText().equals("")) {
            edtNameOfGroup.setText("username");
            edtNameOfGroup.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_edtNameOfGroupFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCreate;
    private javax.swing.JLabel btnSearch;
    private javax.swing.JTextField edtNameOfGroup;
    private javax.swing.JTextField edtSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblFriend;
    private javax.swing.JTable tblMember;
    // End of variables declaration//GEN-END:variables
}
