/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ClientFrame;
import java.awt.Color;
import java.awt.List;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.ArrayList;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Group;
import model.Message;
import model.User;

/**
 *
 * @author Chuong
 */
public class HomeForm extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form HomeForm
     */
    private Socket socket;
    private ObjectInputStream ois;
    private ObjectOutputStream oos;
    private User user;
    StringTokenizer tokenizer;
    private boolean isRunning;
    private Group groupChatNow;
    private ArrayList<Group> listChat1;
    private ArrayList<Group> listGroup;
    Thread thread;
    private ArrayList<User> listFriend1;
    private ArrayList<Message> listMessage;
    private String textMessage = "";

    public HomeForm(Socket socket, User user, ObjectInputStream ois, ObjectOutputStream oos) throws IOException {
        initComponents();
        this.socket = socket;
        this.user = user;
        System.out.println(user.getListGroup().size());
        groupChatNow = new Group();
        this.listGroup = new ArrayList<>();
        this.listChat1 = new ArrayList<>();
        this.ois = ois;
        this.oos = oos;
        txtNameUser.setText(user.getName());
        txtAddressUser.setText(user.getAddress());
        this.listFriend1 = (ArrayList<User>) user.getListFriend();
        txtNameUser.setText("Name user: " + user.getName());
        txtAddressUser.setText("Address: " + user.getAddress());
        createDataListChat();
        oos.writeObject("CMD_LOGIN_CHAT|"+user.getUserId());
        isRunning = true;
        thread=new Thread(this);
        thread.start();
        setTableListChat();
        setTableListFriend();
        setTabletblListGroup();
    }

    public void createDataListChat() {
        for (Group group : user.getListGroup()) {
            if (group.getListMembers().size() > 2) {
                this.listGroup.add(group);
            } else {
                this.listChat1.add(group);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        lstChatSimple = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblListChat = new javax.swing.JTable();
        lstGroupChatSimple = new javax.swing.JPanel();
        btnCreateGroup = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblListGroup = new javax.swing.JTable();
        lstFriend = new javax.swing.JPanel();
        btnAddFriend = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        listFriend = new javax.swing.JTable();
        txtNameUser = new javax.swing.JLabel();
        txtAddressUser = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAShowMessage = new javax.swing.JTextArea();
        edtMessage = new javax.swing.JTextField();
        btnSend = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtNameReceiver = new javax.swing.JLabel();
        txtStatus = new javax.swing.JLabel();
        btnIcon = new javax.swing.JLabel();
        btnImage = new javax.swing.JLabel();
        btnFile = new javax.swing.JLabel();
        edtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JLabel();
        logOut = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");
        setBackground(new java.awt.Color(204, 255, 255));

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        lstChatSimple.setBackground(new java.awt.Color(255, 255, 255));

        tblListChat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblListChat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListChatMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblListChat);

        javax.swing.GroupLayout lstChatSimpleLayout = new javax.swing.GroupLayout(lstChatSimple);
        lstChatSimple.setLayout(lstChatSimpleLayout);
        lstChatSimpleLayout.setHorizontalGroup(
            lstChatSimpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
        );
        lstChatSimpleLayout.setVerticalGroup(
            lstChatSimpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lstChatSimpleLayout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Chat", lstChatSimple);

        lstGroupChatSimple.setBackground(new java.awt.Color(255, 255, 255));

        btnCreateGroup.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCreateGroup.setText("+ new group");
        btnCreateGroup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCreateGroupMouseClicked(evt);
            }
        });
        btnCreateGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateGroupActionPerformed(evt);
            }
        });

        tblListGroup.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tblListGroup);

        javax.swing.GroupLayout lstGroupChatSimpleLayout = new javax.swing.GroupLayout(lstGroupChatSimple);
        lstGroupChatSimple.setLayout(lstGroupChatSimpleLayout);
        lstGroupChatSimpleLayout.setHorizontalGroup(
            lstGroupChatSimpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lstGroupChatSimpleLayout.createSequentialGroup()
                .addComponent(btnCreateGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(lstGroupChatSimpleLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        lstGroupChatSimpleLayout.setVerticalGroup(
            lstGroupChatSimpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lstGroupChatSimpleLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(btnCreateGroup))
        );

        jTabbedPane1.addTab("Group", lstGroupChatSimple);

        lstFriend.setBackground(new java.awt.Color(255, 255, 255));

        btnAddFriend.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAddFriend.setText("+ add friend");
        btnAddFriend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddFriendMouseClicked(evt);
            }
        });
        btnAddFriend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFriendActionPerformed(evt);
            }
        });

        listFriend.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        listFriend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listFriendMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(listFriend);

        javax.swing.GroupLayout lstFriendLayout = new javax.swing.GroupLayout(lstFriend);
        lstFriend.setLayout(lstFriendLayout);
        lstFriendLayout.setHorizontalGroup(
            lstFriendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAddFriend, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        lstFriendLayout.setVerticalGroup(
            lstFriendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lstFriendLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddFriend)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Friend", lstFriend);

        txtNameUser.setBackground(new java.awt.Color(255, 255, 255));
        txtNameUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtAddressUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtAShowMessage.setColumns(20);
        txtAShowMessage.setRows(5);
        jScrollPane1.setViewportView(txtAShowMessage);

        edtMessage.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        edtMessage.setForeground(new java.awt.Color(153, 153, 153));
        edtMessage.setText("Message");
        edtMessage.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                edtMessageFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                edtMessageFocusLost(evt);
            }
        });
        edtMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtMessageActionPerformed(evt);
            }
        });

        btnSend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_send_message.png"))); // NOI18N
        btnSend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSendMouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtNameReceiver.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNameReceiver.setText("Name receiver");

        txtStatus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtStatus.setText("Online");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtStatus))
                    .addComponent(txtNameReceiver, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNameReceiver, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtStatus)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnIcon.setBackground(new java.awt.Color(255, 255, 255));
        btnIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_nhan_dan.png"))); // NOI18N

        btnImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_image.png"))); // NOI18N

        btnFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_send_file.png"))); // NOI18N

        edtSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        edtSearch.setForeground(new java.awt.Color(153, 153, 153));
        edtSearch.setText("Search");
        edtSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                edtSearchFocusLost(evt);
            }
            public void focusGained(java.awt.event.FocusEvent evt) {
                edtSearchFocusGained(evt);
            }
        });

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_tim_kiem.png"))); // NOI18N

        logOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_logout.png"))); // NOI18N
        logOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logOutMouseEntered(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtAddressUser, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                                        .addGap(104, 104, 104))
                                    .addComponent(txtNameUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(38, 38, 38))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(edtSearch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(logOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnImage, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFile, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNameUser, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(txtAddressUser, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(logOut, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(edtSearch)
                            .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnIcon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                            .addComponent(btnFile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(edtMessage, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnImage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void edtMessageFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtMessageFocusGained
        // TODO add your handling code here:
        if (edtMessage.getText().equals("Message")) {
            edtMessage.setText("");
            edtMessage.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_edtMessageFocusGained

    private void edtMessageFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtMessageFocusLost
        // TODO add your handling code here:
        if (edtMessage.getText().equals("")) {
            edtMessage.setText("Message");
            edtMessage.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_edtMessageFocusLost

    private void edtSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtSearchFocusGained
        // TODO add your handling code here:
        if (edtSearch.getText().equals("Search")) {
            edtSearch.setText("");
            edtSearch.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_edtSearchFocusGained

    private void edtSearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtSearchFocusLost
        // TODO add your handling code here:
        if (edtSearch.getText().equals("")) {
            edtSearch.setText("Search");
            edtSearch.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_edtSearchFocusLost

    private void edtMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtMessageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtMessageActionPerformed

    private void btnCreateGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateGroupActionPerformed
        try {
            // TODO add your handling code here:
            isRunning=false;
            thread.stop();
            (new AddGroupForm(user, oos, ois)).setVisible(true);
            this.dispose();
            
        } catch (IOException ex) {
            Logger.getLogger(HomeForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(HomeForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCreateGroupActionPerformed

    private void logOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_logOutMouseEntered

    private void logOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutMouseClicked
        try {
            // TODO add your handling code here:
            oos.writeObject("CMD_QUIT_CHAT|" + user.getUserId());
            isRunning=false;
            oos.close();
            ois.close();
            thread.stop();
            (new LoginForm("not connect",oos, ois)).setVisible(true);
            this.dispose();
        } catch (IOException ex) {
            Logger.getLogger(HomeForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_logOutMouseClicked

    private void btnAddFriendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFriendActionPerformed
        // TODO add your handling code here:
//        (new AddFriendForm()).setVisible(true);
//        this.dispose();
    }//GEN-LAST:event_btnAddFriendActionPerformed

    private void listFriendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listFriendMouseClicked
        // TODO add your handling code here:
//        DefaultTableModel dtm = new DefaultTableModel();
//        dtm.setRowCount(0);
//        dtm.setColumnIdentifiers(new String[]{"Nick Name"});
//        if (listFriend1 != null) {
//            for (User friend : listFriend1) {
//                dtm.addRow(new String[]{friend.getName()});
//            }
//        }
//        listFriend.setModel(dtm);
    }//GEN-LAST:event_listFriendMouseClicked

    private void btnAddFriendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddFriendMouseClicked
        try {
            // TODO add your handling code here:
            (new AddFriendForm(user, oos, ois)).setVisible(true);
            this.dispose();
        } catch (IOException ex) {
            Logger.getLogger(HomeForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(HomeForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddFriendMouseClicked

    private void tblListChatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListChatMouseClicked
        // TODO add your handling code here:
        int column = tblListChat.getColumnModel().
                getColumnIndexAtX(evt.getX()); // get the coloum of the button
        int row = evt.getY() / tblListChat.getRowHeight(); // get row 
        // *Checking the row or column is valid or not
        if (row < tblListChat.getRowCount() && row >= 0
                && column < tblListChat.getColumnCount() && column >= 0) {
            Group group = listChat1.get(row);
            groupChatNow = group;
            System.out.println(group.getListUser().size());
            User userReceiver = (group.getListUser().get(0).getName().equals(user.getName())) ? group.getListUser().get(1) : group.getListUser().get(0);
//            String textMessage = "";
            for (int i = 0; i < group.getListMessages().size(); i++) {
                System.out.println(group.getListMessages().get(i).getUser().getName() + ": " + group.getListMessages().get(i).getMessage());
                textMessage += group.getListMessages().get(i).getUser().getName() + ": " + group.getListMessages().get(i).getMessage() + "\n\n";
            }
            txtAShowMessage.setText(textMessage);
            txtNameReceiver.setText(userReceiver.getName());
            if (userReceiver.getActiveStatus() == 0) {
                txtStatus.setText("Offline");
            } else {
                txtStatus.setText("Online");
            }
        }
    }//GEN-LAST:event_tblListChatMouseClicked

    private void btnSendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSendMouseClicked
        try {
            if (!edtMessage.getText().equals("")) {
                // TODO add your handling code here:
                String mess = edtMessage.getText();
                edtMessage.setText("");
                oos.writeObject("CMD_SEND_MESSAGE|" + groupChatNow.getGroupId() + "|" + mess);
            }
        } catch (IOException ex) {
            Logger.getLogger(HomeForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSendMouseClicked

    private void btnCreateGroupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateGroupMouseClicked
        try {
            // TODO add your handling code here:
            (new AddGroupForm(user, oos, ois)).setVisible(true);
            this.dispose();
        } catch (IOException ex) {
            Logger.getLogger(HomeForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(HomeForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCreateGroupMouseClicked
    public void setTableListChat() {
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.setRowCount(0);
        dtm.setColumnIdentifiers(new String[]{"Group Name"});
        if (listChat1 != null) {
            for (Group group : listChat1) {
                dtm.addRow(new String[]{group.getNameGroup()});
            }
        }
        tblListChat.setModel(dtm);
    }

    public void setTableListFriend() {
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.setRowCount(0);
        dtm.setColumnIdentifiers(new String[]{"Nick Name"});
        if (listFriend1 != null) {
            for (User friend : listFriend1) {
                dtm.addRow(new String[]{friend.getName()});
            }
        }
        listFriend.setModel(dtm);
    }

    public void setTabletblListGroup() {

        DefaultTableModel dtm = new DefaultTableModel();
        dtm.setRowCount(0);
        dtm.setColumnIdentifiers(new String[]{"Group Name"});
        if (listGroup != null) {
            for (Group group : listGroup) {
                dtm.addRow(new String[]{group.getNameGroup()});
            }
        }
        tblListGroup.setModel(dtm);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddFriend;
    private javax.swing.JButton btnCreateGroup;
    private javax.swing.JLabel btnFile;
    private javax.swing.JLabel btnIcon;
    private javax.swing.JLabel btnImage;
    private javax.swing.JLabel btnSearch;
    private javax.swing.JLabel btnSend;
    private javax.swing.JTextField edtMessage;
    private javax.swing.JTextField edtSearch;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable listFriend;
    private javax.swing.JLabel logOut;
    private javax.swing.JPanel lstChatSimple;
    private javax.swing.JPanel lstFriend;
    private javax.swing.JPanel lstGroupChatSimple;
    private javax.swing.JTable tblListChat;
    private javax.swing.JTable tblListGroup;
    private javax.swing.JTextArea txtAShowMessage;
    private javax.swing.JLabel txtAddressUser;
    private javax.swing.JLabel txtNameReceiver;
    private javax.swing.JLabel txtNameUser;
    private javax.swing.JLabel txtStatus;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {

        String response = "";
        String sender, receiver, fileName, thePersonIamChattingWith, thePersonSendFile;
        String msg;
        String cmd, icon;
        PrivateChat pc;

        while (isRunning) {
            try {
                response = (String) ois.readObject();
            } catch (IOException ex) {
                Logger.getLogger(HomeForm.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(HomeForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            tokenizer = new StringTokenizer(response, "|");
            cmd = tokenizer.nextToken();
            switch (cmd) {
                case "CMD_CHAT":    //giả sử nhận được gói tin: CMD_CHAT|anh tu: today is very cool!
//                  "CMD_CHAT|"+String.valueOf(m.getMessId())+"|"+String.valueOf(m.getUser().getUserId())+"|"+m.getMessage()+"|"+String.valueOf(m.getGroupId())
                    int messId = Integer.parseInt(tokenizer.nextToken());
                    int userId = Integer.parseInt(tokenizer.nextToken());
                    System.out.println(userId);
                    Group groupReceiver = new Group();
                    User userReceiver = new User();
                    Message ms = new Message();
                    String message = tokenizer.nextToken();
                    int groupId = Integer.parseInt(tokenizer.nextToken());
                    for (int i = 0; i < user.getListGroup().size(); i++) {
                        if (user.getListGroup().get(i).getGroupId() == groupId) {
                            ms = new Message(messId, user, message, groupId);
                            user.getListGroup().get(i).getListMessages().add(ms);
                            for (User user : user.getListGroup().get(i).getListUser()) {
                                if (user.getUserId() == userId) {
                                    userReceiver = user;
                                    System.out.println(userReceiver.getName());
                                }
                            }
                            createDataListChat();
                            break;
                        }
                    }
                    if (groupId == groupChatNow.getGroupId()) {
                        String mess = txtAShowMessage.getText();
                        groupChatNow.getListMessages().add(ms);
                        mess += userReceiver.getName() + ": " + message + "\n\n";
                        txtAShowMessage.setText(mess);
                        //edtMessage.setText("");
                    }
                    break;

                case "CMD_UPDATE_STATUS_CLIENT":
                    int userid = Integer.parseInt(tokenizer.nextToken());
                    int status = Integer.parseInt(tokenizer.nextToken());
                    System.out.println("user moi dang nhap "+userid);
                    for (int i = 0; i < listFriend1.size(); i++) {
                        if (listFriend1.get(i).getUserId() == userid) {
                            listFriend1.get(i).setActiveStatus(status);
                        }
                    }
                    for (int i = 0; i < listChat1.size(); i++) {
                        for (int j = 0; j < listChat1.get(i).getListUser().size(); j++) {
                            if (listChat1.get(i).getListUser().get(j).getUserId() == userid) {
                                listChat1.get(i).getListUser().get(j).setActiveStatus(status);
                                if(listChat1.get(i).getGroupId()==groupChatNow.getGroupId()){
                                    if(status==1) txtStatus.setText("Online");
                                    else txtStatus.setText("Offline");
                                }
                            }
                        }
                    }
                    break;
                default:

                //do bên server có hàm notifyToAllUsers(clientName+" has just entered!"); 
                //hàm trên ko có định dạng nào cả, tức là ko có CMD_ ở đầu message, nên ta chỉ cần in ra thông điệp server gửi tới là đc
            }
        }
        System.out.println("Disconnected to server!");
    }
}
