/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import java.awt.Color;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.User;

/**
 *
 * @author Chuong
 */
public class SignupForm extends javax.swing.JFrame {

    public static final String NICKNAME_EXIST = "This nickname is already login in another place! Please using another nickname";
    public static final String NICKNAME_VALID = "This nickname is OK";
    public static final String NICKNAME_INVALID = "Nickname or password is incorrect";
    public static final String SIGNUP_SUCCESS = "Sign up successful!";
    public static final String ACCOUNT_EXIST = "This nickname has been used! Please use another nickname!";
    public static final String PASSWORD_CONFIRM = "Passwords don't match!";
    
    private Socket socketOfClient;
    private ObjectOutputStream oos;
    private ObjectInputStream ois;
    private boolean isConnectToServer;
    private String serverHost;

    /**
     * Creates new form SignupForm
     */
    public SignupForm(ObjectOutputStream oos,ObjectInputStream ois) throws IOException {
        this.oos = oos;
        this.ois = ois;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        edtUserName = new javax.swing.JTextField();
        btnSignUp = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        edtName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        edtAddress = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        edtPassWord = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        edtConfirmPassword = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SignUp");
        setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Sign Up");

        edtUserName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        edtUserName.setForeground(new java.awt.Color(153, 153, 153));
        edtUserName.setText("Username");
        edtUserName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                edtUserNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                edtUserNameFocusLost(evt);
            }
        });

        btnSignUp.setBackground(new java.awt.Color(255, 255, 255));
        btnSignUp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSignUp.setText("Sign up");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Username:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Name:");

        edtName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        edtName.setForeground(new java.awt.Color(153, 153, 153));
        edtName.setText("Your name");
        edtName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                edtNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                edtNameFocusLost(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Address:");

        edtAddress.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        edtAddress.setForeground(new java.awt.Color(153, 153, 153));
        edtAddress.setText("Address");
        edtAddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                edtAddressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                edtAddressFocusLost(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("PassWord:");

        edtPassWord.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        edtPassWord.setForeground(new java.awt.Color(153, 153, 153));
        edtPassWord.setText("Password");
        edtPassWord.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                edtPassWordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                edtPassWordFocusLost(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Confirm PassWord:");

        edtConfirmPassword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        edtConfirmPassword.setForeground(new java.awt.Color(153, 153, 153));
        edtConfirmPassword.setText("Password");
        edtConfirmPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                edtConfirmPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                edtConfirmPasswordFocusLost(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Signup.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(edtUserName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edtAddress, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edtName)
                            .addComponent(edtPassWord)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSignUp)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(edtConfirmPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(511, 511, 511)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel6)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel7)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel5)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(edtName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(edtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(edtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(edtPassWord, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel9))
                    .addComponent(edtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btnSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void edtNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtNameFocusGained
        // TODO add your handling code here:

        if (edtName.getText().equals("Your name")) {
            edtName.setText("");
            edtName.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_edtNameFocusGained

    private void edtNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtNameFocusLost
        // TODO add your handling code here:
        if (edtName.getText().equals("")) {
            edtName.setText("Your name");
            edtName.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_edtNameFocusLost

    private void edtAddressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtAddressFocusGained
        // TODO add your handling code here:
        if (edtAddress.getText().equals("Address")) {
            edtAddress.setText("");
            edtAddress.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_edtAddressFocusGained

    private void edtAddressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtAddressFocusLost
        // TODO add your handling code here:
        if (edtAddress.getText().equals("")) {
            edtAddress.setText("Address");
            edtAddress.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_edtAddressFocusLost

    private void edtUserNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtUserNameFocusGained
        // TODO add your handling code here:
        if (edtUserName.getText().equals("Username")) {
            edtUserName.setText("");
            edtUserName.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_edtUserNameFocusGained

    private void edtUserNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtUserNameFocusLost
        // TODO add your handling code here:
        if (edtUserName.getText().equals("")) {
            edtUserName.setText("Username");
            edtUserName.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_edtUserNameFocusLost

    private void edtPassWordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtPassWordFocusGained
        // TODO add your handling code here:
        if (edtPassWord.getText().equals("Password")) {
            edtPassWord.setText("");
            edtPassWord.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_edtPassWordFocusGained

    private void edtPassWordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtPassWordFocusLost
        // TODO add your handling code here:
        if (edtPassWord.getText().equals("")) {
            edtPassWord.setText("Password");
            edtPassWord.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_edtPassWordFocusLost

    private void edtConfirmPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtConfirmPasswordFocusGained
        // TODO add your handling code here:
        if (edtConfirmPassword.getText().equals("Password")) {
            edtConfirmPassword.setText("");
            edtConfirmPassword.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_edtConfirmPasswordFocusGained

    private void edtConfirmPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtConfirmPasswordFocusLost
        // TODO add your handling code here:
        if (edtConfirmPassword.getText().equals("")) {
            edtConfirmPassword.setText("Password");
            edtConfirmPassword.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_edtConfirmPasswordFocusLost

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        // TODO add your handling code here:
        User user=new User();
        user.setName(edtName.getText());
        user.setAddress(edtAddress.getText());
        user.setUserName(edtUserName.getText());
        user.setPassWord(edtPassWord.getText());
        user.setActiveStatus(0);
        String confirmPass=edtConfirmPassword.getText();
        if(!user.getPassWord().equals(confirmPass)) {
            JOptionPane.showMessageDialog(this, "Passwords don't match!");
        } else {
            if(user.getName().equals("")|| user.getUserName().equals("")|| user.getAddress().equals("")||user.getPassWord().equals("")||confirmPass.equals("")) {
                JOptionPane.showMessageDialog(this, "Please fill up all fields");
            }
            
            try {
                oos.writeObject("CMD_SIGN_UP|" +user.getName()+"|"+user.getAddress()+"|"+user.getUserName()+"|"+user.getPassWord());       //sau đó gửi tên đến để yêu cầu đăng nhập =  tên đó
            } catch (IOException ex) {
                Logger.getLogger(SignupForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        
            String response=null;
            try {
                response = (String) ois.readObject();
            } catch (IOException ex) {
                Logger.getLogger(SignupForm.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(SignupForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            if(response != null) {
                System.out.println(response);
                if(response.equals(NICKNAME_EXIST) || response.equals(ACCOUNT_EXIST)) {
                    JOptionPane.showMessageDialog(this, response);
                } else {
                    JOptionPane.showMessageDialog(this, "Success");
                    try {
   
                        (new LoginForm("connected",oos,ois)).setVisible(true);
                        this.dispose();
                    } catch (IOException ex) {
                        Logger.getLogger(SignupForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                }
            }
        }
        
    }//GEN-LAST:event_btnSignUpActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSignUp;
    private javax.swing.JTextField edtAddress;
    private javax.swing.JTextField edtConfirmPassword;
    private javax.swing.JTextField edtName;
    private javax.swing.JTextField edtPassWord;
    private javax.swing.JTextField edtUserName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
